Cypress.Commands.add('enviarReceitaSucesso', () => {
    cy.get('label[for=file-uploader]').selectFile('cypress/fixtures/receita.png')
    cy.get('input[name=zip]').type('13231090')
    cy.get('input[type=email]').type('emailteste@gmail.com')
    cy.get('input[name=name]').type('Hanrrison Oliveira')
    cy.get('input[type=tel]').type('11975621174')
    cy.get('input[type=checkbox]').check({force: true})
    cy.get('button[type=submit]').contains('Enviar Receita').click()
    cy.contains('h2', 'Receita enviada com sucesso!')
})

Cypress.Commands.add('enviarReceitaFalha', () => {
    cy.get('label[for=file-uploader]').selectFile('cypress/fixtures/receita2.jpg')
    cy.get('input[name=zip]').type('69917-740')
    cy.get('input[type=email]').type('emailteste@gmail.com')
    cy.get('input[name=name]').type('Cliente do Acre')
    cy.get('input[type=tel]').type('11975621174')
    cy.get('input[type=checkbox]').check({force: true})
    cy.get('button[type=submit]').contains('Enviar Receita').click()
    cy.contains('h2', 'Que pena. Ainda não atendemos sua região.')
})